# Site settings
title: The White Hat - Cal Poly SLO
description: >
  The White Hat’s mission is to provide the tools, knowledge, skills and
  resources to make the internet a safer place by protecting personal computers,
  private data and information systems.
url: "https://thewhitehat.club"

exclude: ["README.md"]

# Build settings
markdown: kramdown

compress_html:
  clippings: all
  comments: all

sass:
  style: compressed
